version: 2.1

orbs:
  ghpr: narrativescience/ghpr@0.0.5

commands:
  install-deps:
    description: Install dependencies and initialize pre-commit hooks
    steps:
      - run:
          command: |
            pip install pre-commit tox flit
            pre-commit install
          name: Install dependencies

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - ghpr/build-prospective-branch
      - install-deps
      - run:
          name: Run commit hooks
          command: |
            pre-commit run \
              --source "origin/${GITHUB_PR_BASE_BRANCH}" \
              --origin "origin/${CIRCLE_BRANCH}" \
              --show-diff-on-failure
      - run: tox
      - run: flit build
      - ghpr/post-pr-comment:
          comment: Tests failed!
          when: on_fail
  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install flit
      - run: flit build
      - run: flit publish

workflows:
  pull_request:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
