version: 2.1

orbs:
  ghpr: narrativescience/ghpr@0.0.5

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - ghpr/build-prospective-branch
      - run:
          name: Install dependencies
          command: |
            pip install poetry
            poetry install
            poetry run pre-commit install
      - run:
          name: Run commit hooks
          command: |
            poetry run pre-commit run \
              --source "origin/${GITHUB_PR_BASE_BRANCH}" \
              --origin "origin/${CIRCLE_BRANCH}" \
              --show-diff-on-failure
      - run: poetry build
      # - run: poetry run pytest
      - ghpr/post-pr-comment:
          comment: Tests failed!
          when: on_fail
  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: poetry build
      - run: poetry publish

workflows:
  pull_request:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
